/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const ElTag: typeof import('element-plus/es')['ElTag']
}
